# Generated by Django 4.1.3 on 2023-01-29 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Brecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('inicio', models.TimeField()),
                ('final', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('duracion', models.DurationField()),
                ('valor', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_per_appointment', models.IntegerField(default=30)),
                ('start_date', models.DateField()),
                ('monday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('monday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('tuesday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('tuesday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('wednesday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('wednesday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('thursday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('thursday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('friday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('friday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('saturday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('saturday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('sunday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('sunday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(unique=True)),
                ('time_period', models.DurationField()),
                ('is_limit', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='appointments.appointment')),
                ('brecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.brecha')),
            ],
        ),
    ]
