# Generated by Django 4.1.3 on 2023-02-01 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_final_appointment_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='servicio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='appointments.servicio'),
        ),
    ]
