# Generated by Django 4.1.3 on 2023-01-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_gap_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
