# Generated by Django 4.1.3 on 2023-01-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
